name: Deploying
on:
  # push:
  pull_request:
    branches:
      - development
jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: list directory
        uses: the-coding-turtle/ga-file-list@v0.2
      - name: Deploying timetable to appstore
        run: cd ..; fastlane timetable_appstore