name: Deploying
on:
  # push:
  pull_request:
    branches:
      - development
jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    steps:
      - name: Deploying timetable to appstore
        run: sudo fastlane timetable_appstore